load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load(":sha256sum_tool.bzl", "sha256sum_tool")

sha256sum_tool(
    name = "sha256sum_tool",
)

bzl_library(
    name = "bazel_env",
    srcs = [
        "bazel_env.bzl",
        "sha256sum_tool.bzl",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@bazel_features//:features",
        "@bazel_skylib//rules:write_file",
    ],
)

exports_files(
    ["bazel_env.bzl"],
    visibility = ["//docs:__pkg__"],
)

exports_files(
    [
        "status.sh.tpl",
        "launcher.sh.tpl",
        "lock_lib.sh",
    ],
    visibility = ["//visibility:private"],
)
